Secrets:
  AccessTokenSecret: "CzXyrohAwqohwqSewqRrweqtwer"
  RefreshTokenSecret: "CzXyralAbdaEbdkaCqewqwrqwrfqw"

TokenExpiry:
  AccessTokenExpiry: 7200  # 2 小时
  RefreshTokenExpiry: 604800  # 7 天

Redis:
  Address: "127.0.0.1:6379"
  Username: ""
  Password: ""
  DB: 0

Registry:
  RegistryAddress:
    - 127.0.0.1:2379
  Username: ""
  Password: ""