// Code generated by Kitex v0.12.3. DO NOT EDIT.

package authservice

import (
	"context"
	auth_service "github.com/ITu-CloudWeGo/itu_rpc_auth/rpc/kitex_gen/auth_service"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAuth(ctx context.Context, Req *auth_service.CreateAuthReq, callOptions ...callopt.Option) (r *auth_service.CreateAuthResp, err error)
	UpdateAuth(ctx context.Context, Req *auth_service.UpdateAuthReq, callOptions ...callopt.Option) (r *auth_service.UpdateAuthResp, err error)
	Email(ctx context.Context, Req *auth_service.EmailReq, callOptions ...callopt.Option) (r *auth_service.EmailResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) CreateAuth(ctx context.Context, Req *auth_service.CreateAuthReq, callOptions ...callopt.Option) (r *auth_service.CreateAuthResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAuth(ctx, Req)
}

func (p *kAuthServiceClient) UpdateAuth(ctx context.Context, Req *auth_service.UpdateAuthReq, callOptions ...callopt.Option) (r *auth_service.UpdateAuthResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAuth(ctx, Req)
}

func (p *kAuthServiceClient) Email(ctx context.Context, Req *auth_service.EmailReq, callOptions ...callopt.Option) (r *auth_service.EmailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Email(ctx, Req)
}
