// Code generated by Kitex v0.12.3. DO NOT EDIT.

package authservice

import (
	"context"
	auth_service "github.com/ITu-CloudWeGo/itu_rpc_auth/rpc/kitex_gen/auth_service"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenerateToken(ctx context.Context, Req *auth_service.GenerateTokenRequest, callOptions ...callopt.Option) (r *auth_service.GenerateTokenResponse, err error)
	RefreshToken(ctx context.Context, Req *auth_service.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth_service.RefreshTokenResponse, err error)
	CheckAccessToken(ctx context.Context, Req *auth_service.CheckAccessTokenRequest, callOptions ...callopt.Option) (r *auth_service.CheckAccessTokenResponse, err error)
	CheckRefreshToken(ctx context.Context, Req *auth_service.CheckRefreshTokenRequest, callOptions ...callopt.Option) (r *auth_service.CheckRefreshTokenResponse, err error)
	Email(ctx context.Context, Req *auth_service.EmailRequest, callOptions ...callopt.Option) (r *auth_service.EmailResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) GenerateToken(ctx context.Context, Req *auth_service.GenerateTokenRequest, callOptions ...callopt.Option) (r *auth_service.GenerateTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateToken(ctx, Req)
}

func (p *kAuthServiceClient) RefreshToken(ctx context.Context, Req *auth_service.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth_service.RefreshTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, Req)
}

func (p *kAuthServiceClient) CheckAccessToken(ctx context.Context, Req *auth_service.CheckAccessTokenRequest, callOptions ...callopt.Option) (r *auth_service.CheckAccessTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckAccessToken(ctx, Req)
}

func (p *kAuthServiceClient) CheckRefreshToken(ctx context.Context, Req *auth_service.CheckRefreshTokenRequest, callOptions ...callopt.Option) (r *auth_service.CheckRefreshTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckRefreshToken(ctx, Req)
}

func (p *kAuthServiceClient) Email(ctx context.Context, Req *auth_service.EmailRequest, callOptions ...callopt.Option) (r *auth_service.EmailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Email(ctx, Req)
}
